-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.8
-- Thu May  9 17:13:50 2019

-- parameterized module component declaration
component fmexg_fifo_5
    port (Data: in  std_logic_vector(11 downto 0); 
        WrClock: in  std_logic; RdClock: in  std_logic; 
        WrEn: in  std_logic; RdEn: in  std_logic; Reset: in  std_logic; 
        RPReset: in  std_logic; Q: out  std_logic_vector(11 downto 0); 
        Empty: out  std_logic; Full: out  std_logic; 
        AlmostEmpty: out  std_logic; AlmostFull: out  std_logic);
end component;

-- parameterized module component instance
__ : fmexg_fifo_5
    port map (Data(11 downto 0)=>__, WrClock=>__, RdClock=>__, WrEn=>__, 
        RdEn=>__, Reset=>__, RPReset=>__, Q(11 downto 0)=>__, Empty=>__, 
        Full=>__, AlmostEmpty=>__, AlmostFull=>__);
