.TH "osp Directory Reference" 3 "Thu Jun 14 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
osp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBscripts\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlogger\&.c\fP"
.br
.ti -1c
.RI "file \fBlogger\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBport_wrapper\&.c\fP"
.br
.ti -1c
.RI "file \fBport_wrapper\&.h\fP"
.br
.in -1c
