.TH "libosp/beam_forming Directory Reference" 3 "Mon Oct 8 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp/beam_forming Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbeam_forming\&.c\fP"
.br
.ti -1c
.RI "file \fBbeam_forming\&.h\fP"
.br
.ti -1c
.RI "file \fBdelay_line\&.c\fP"
.br
.ti -1c
.RI "file \fBdelay_line\&.h\fP"
.br
.in -1c
