.TH "libosp Directory Reference" 3 "Fri Feb 23 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBafc\fP"
.br
.ti -1c
.RI "directory \fBarray_utilities\fP"
.br
.ti -1c
.RI "directory \fBbeam_forming\fP"
.br
.ti -1c
.RI "directory \fBcommon\fP"
.br
.ti -1c
.RI "directory \fBfilter\fP"
.br
.ti -1c
.RI "directory \fBosp_process\fP"
.br
.ti -1c
.RI "directory \fBosp_tcp\fP"
.br
.ti -1c
.RI "directory \fBpeak_detect\fP"
.br
.ti -1c
.RI "directory \fBresample\fP"
.br
.ti -1c
.RI "directory \fBspeech_enhancement\fP"
.br
.ti -1c
.RI "directory \fBwdrc\fP"
.br
.in -1c
