.TH "libosp/afc Directory Reference" 3 "Fri Feb 23 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp/afc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBafc\&.c\fP"
.br
.ti -1c
.RI "file \fBafc\&.h\fP"
.br
.ti -1c
.RI "file \fBcircular_buffer\&.c\fP"
.br
.ti -1c
.RI "file \fBcircular_buffer\&.h\fP"
.br
.in -1c
