.TH "libosp/wdrc Directory Reference" 3 "Wed Jun 13 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp/wdrc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmpo\&.c\fP"
.br
.ti -1c
.RI "file \fBmpo\&.h\fP"
.br
.ti -1c
.RI "file \fBwdrc\&.c\fP"
.br
.ti -1c
.RI "file \fBwdrc\&.h\fP"
.br
.ti -1c
.RI "file \fBwdrc_mpo_support\&.c\fP"
.br
.ti -1c
.RI "file \fBwdrc_mpo_support\&.h\fP"
.br
.in -1c
