.TH "libosp/array_utilities Directory Reference" 3 "Fri Feb 23 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp/array_utilities Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBarray_utilities\&.c\fP"
.br
.ti -1c
.RI "file \fBarray_utilities\&.h\fP"
.br
.in -1c
