.TH "libosp/osp_tcp Directory Reference" 3 "Thu Jun 14 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp/osp_tcp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBjson_parser\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBosp_tcp\&.c\fP"
.br
.ti -1c
.RI "file \fBosp_tcp\&.h\fP"
.br
.ti -1c
.RI "file \fBtcplib\&.c\fP"
.br
.ti -1c
.RI "file \fBtcplib\&.h\fP"
.br
.in -1c
