.TH "libosp/peak_detect Directory Reference" 3 "Mon Oct 8 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp/peak_detect Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpeak_detect\&.c\fP"
.br
.ti -1c
.RI "file \fBpeak_detect\&.h\fP"
.br
.in -1c
