.TH "libosp/beam_forming/beam_forming.c" 3 "Thu Jun 14 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp/beam_forming/beam_forming.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'beam_forming\&.h'\fP
.br
\fC#include 'delay_line\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBbeam_form_t\fP"
.br
.RI "data structure containing relevant beam-forming fields "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDISTANCE\fP   0\&.1"
.br
.RI "Distance between front and rear microphones in meters\&. "
.ti -1c
.RI "#define \fBSPEED_OF_SOUND\fP   340\&.29"
.br
.RI "Speed of sound in meters/second\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBeam_Form\fP \fBbeam_form_init\fP (float beta, float gain, float sample_rate)"
.br
.RI "Initialization function for the beam forming data struct\&. "
.ti -1c
.RI "void \fBbeam_form_proc\fP (\fBBeam_Form\fP beam_form, float *in_front, float *in_rear, float *output, int len)"
.br
.RI "Takes in two channel inputs, and attempts to use beamforming to provide directed output The in_front, in_rear, and output arrays must be allocated so that they are len samples long\&. "
.ti -1c
.RI "void \fBbeam_form_destroy\fP (\fBBeam_Form\fP beam_form)"
.br
.RI "Closes and frees the beam_form instance\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DISTANCE   0\&.1"

.PP
Distance between front and rear microphones in meters\&. 
.SS "#define SPEED_OF_SOUND   340\&.29"

.PP
Speed of sound in meters/second\&. 
.SH "Function Documentation"
.PP 
.SS "void beam_form_destroy (\fBBeam_Form\fP beam_form)"

.PP
Closes and frees the beam_form instance\&. 
.PP
\fBSee also:\fP
.RS 4
\fBbeam_form_t\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeam_form\fP The instance of the Beam_Form variable that was returned from beam_form_init 
.RE
.PP

.SS "\fBBeam_Form\fP beam_form_init (float beta, float gain, float sample_rate)"

.PP
Initialization function for the beam forming data struct\&. 
.PP
\fBSee also:\fP
.RS 4
\fBbeam_form_t\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeta\fP beta value 
.br
\fIgain\fP gain value 
.br
\fIsample_rate\fP Sample rate set by audio drivers\&. Used in calculation of angle 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns the allocated instance of the beamforming data structure ('object') 
.RE
.PP

.SS "void beam_form_proc (\fBBeam_Form\fP beam_form, float * in_front, float * in_rear, float * output, int len)"

.PP
Takes in two channel inputs, and attempts to use beamforming to provide directed output The in_front, in_rear, and output arrays must be allocated so that they are len samples long\&. 
.PP
\fBSee also:\fP
.RS 4
\fBbeam_form_t\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIbeam_form\fP The instance of the Beam_Form variable that was returned from beam_form_init 
.br
\fIin_front\fP Float array of the input samples from the 'front' mic that are len floats long 
.br
\fIin_rear\fP Float array of the samples from the 'rear' mic that are len floats long 
.br
\fIoutput\fP Float array containing the processed samples that are len floats long 
.br
\fIlen\fP The length of the input 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
