.TH "circular_buffer_t" 3 "Fri Feb 23 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
circular_buffer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float * \fBbuf\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.ti -1c
.RI "size_t \fBindex\fP"
.br
.ti -1c
.RI "size_t \fBbuf_len\fP"
.br
.ti -1c
.RI "unsigned char \fBexp\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float* circular_buffer_t::buf"

.SS "size_t circular_buffer_t::buf_len"

.SS "unsigned char circular_buffer_t::exp"

.SS "size_t circular_buffer_t::index"

.SS "size_t circular_buffer_t::length"


.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
