.TH "libosp/osp_process/coeffs.h" 3 "Mon Oct 8 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp/osp_process/coeffs.h
.SH SYNOPSIS
.br
.PP
\fC#include 'constants\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBARRAY_SIZE\fP(x)   (sizeof((x)) / sizeof((x)[0]))"
.br
.ti -1c
.RI "#define \fBHPF_TAPS\fP   4"
.br
.RI "Pre-whitening filter tap length\&. "
.ti -1c
.RI "#define \fBBLF_TAPS\fP   4"
.br
.RI "Band-limited filter tap length\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const float \fBhpf_taps\fP [\fBHPF_TAPS\fP]"
.br
.RI "Pre-whitening filter taps\&. "
.ti -1c
.RI "static const float \fBblf_taps\fP [\fBBLF_TAPS\fP]"
.br
.RI "Band-limited filter taps\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARRAY_SIZE(x)   (sizeof((x)) / sizeof((x)[0]))"

.SS "#define BLF_TAPS   4"

.PP
Band-limited filter tap length\&. 
.SS "#define HPF_TAPS   4"

.PP
Pre-whitening filter tap length\&. 
.SH "Variable Documentation"
.PP 
.SS "const float blf_taps[\fBBLF_TAPS\fP]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    -0\&.0876,
    -0\&.7904,
    0\&.7904,
    0\&.0876
}
.fi
.PP
Band-limited filter taps\&. 
.SS "const float hpf_taps[\fBHPF_TAPS\fP]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    0\&.1170,
    -0\&.6034,
    0\&.6034,
    -0\&.1170
}
.fi
.PP
Pre-whitening filter taps\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
