.TH "osp/scripts/extract_bin.c" 3 "Mon Oct 8 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
osp/scripts/extract_bin.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static int \fBprint_header\fP (FILE *in_file, FILE *out_file, char *file_name)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SS "static int print_header (FILE * in_file, FILE * out_file, char * file_name)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
