.TH "file_loopback_context_t" 3 "Thu Jun 14 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_loopback_context_t \- Struct containing details for file loopback mode\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <port_wrapper\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "FILE * \fBinput_file\fP"
.br
.RI "Input file\&. "
.ti -1c
.RI "FILE * \fBoutput_file\fP"
.br
.RI "Output file\&. "
.ti -1c
.RI "unsigned long \fBlength\fP"
.br
.RI "Number of samples in input file\&. "
.ti -1c
.RI "unsigned long \fBindex\fP"
.br
.RI "Internal index var\&. "
.ti -1c
.RI "char \fBwav_header\fP [44]"
.br
.RI "Header data embedded in \&.wav file\&. "
.ti -1c
.RI "float * \fBinL\fP"
.br
.RI "Array of input left samples\&. "
.ti -1c
.RI "float * \fBinR\fP"
.br
.RI "Array of input right samples\&. "
.ti -1c
.RI "float * \fBoutL\fP"
.br
.RI "Array of output left samples\&. "
.ti -1c
.RI "float * \fBoutR\fP"
.br
.RI "Array of output right samples\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct containing details for file loopback mode\&. 
.SH "Field Documentation"
.PP 
.SS "unsigned long file_loopback_context_t::index"

.PP
Internal index var\&. 
.SS "float* file_loopback_context_t::inL"

.PP
Array of input left samples\&. 
.SS "FILE* file_loopback_context_t::input_file"

.PP
Input file\&. 
.SS "float* file_loopback_context_t::inR"

.PP
Array of input right samples\&. 
.SS "unsigned long file_loopback_context_t::length"

.PP
Number of samples in input file\&. 
.SS "float* file_loopback_context_t::outL"

.PP
Array of output left samples\&. 
.SS "FILE* file_loopback_context_t::output_file"

.PP
Output file\&. 
.SS "float* file_loopback_context_t::outR"

.PP
Array of output right samples\&. 
.SS "char file_loopback_context_t::wav_header[44]"

.PP
Header data embedded in \&.wav file\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
