.TH "jsmntok_t" 3 "Mon Oct 8 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsmntok_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jsmn\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBjsmntype_t\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "int \fBend\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
JSON token description\&. type type (object, array, string etc\&.) start start position in JSON data string end end position in JSON data string 
.SH "Field Documentation"
.PP 
.SS "int jsmntok_t::end"

.SS "int jsmntok_t::size"

.SS "int jsmntok_t::start"

.SS "\fBjsmntype_t\fP jsmntok_t::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
