.TH "jsmn_parser" 3 "Thu Jun 14 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jsmn_parser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jsmn\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBpos\fP"
.br
.ti -1c
.RI "unsigned int \fBtoknext\fP"
.br
.ti -1c
.RI "int \fBtoksuper\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
JSON parser\&. Contains an array of token blocks available\&. Also stores the string being parsed now and current position in that string 
.SH "Field Documentation"
.PP 
.SS "unsigned int jsmn_parser::pos"

.SS "unsigned int jsmn_parser::toknext"

.SS "int jsmn_parser::toksuper"


.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
