.TH "osp/main.c" 3 "Wed Jun 13 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
osp/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <execinfo\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <ifaddrs\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include 'osp_tcp\&.h'\fP
.br
\fC#include 'osp_process\&.h'\fP
.br
\fC#include 'resample\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br
\fC#include 'port_wrapper\&.h'\fP
.br
\fC#include 'constants\&.h'\fP
.br
\fC#include 'logger\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUI_PORT\fP   8001"
.br
.ti -1c
.RI "#define \fBSAMPLE_RATE\fP   96000"
.br
.ti -1c
.RI "#define \fBFRAMES_PER_BUFFER\fP   96"
.br
.ti -1c
.RI "#define \fBD_ATTENUATION_FACTOR\fP   (0\&.025)"
.br
.ti -1c
.RI "#define \fBARRAY_SIZE\fP(x)   (sizeof((x)) / sizeof((x)[0]))"
.br
.ti -1c
.RI "#define \fBOPT_STRING\fP   'Enter \\'a\\' to enable hearing aid algorithm, \\'d\\' to disable \\'q\\' to quit\\n'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static float \fBlog2lin\fP (float db)"
.br
.ti -1c
.RI "static void \fBusage\fP (const char *s)"
.br
.ti -1c
.RI "static void * \fBannounce_presence\fP (void *tid)"
.br
.ti -1c
.RI "static void \fBrun_loopback\fP (\fBosp_user_data\fP *osp_data, float *inL, float *inR, float *outL, float *outR, size_t len)"
.br
.ti -1c
.RI "static int \fBfile_loopback_init\fP (\fBfile_loopback_context\fP *ctx, const char *in_file, const char *out_file)"
.br
.ti -1c
.RI "static void \fBfile_loopback_close\fP (\fBfile_loopback_context\fP *ctx)"
.br
.ti -1c
.RI "static int \fBfile_context_write\fP (\fBfile_loopback_context\fP *file_ctx)"
.br
.ti -1c
.RI "static int \fBfile_loopback_run\fP (const char *in_file, const char *out_file, unsigned int frames_per_buffer)"
.br
.ti -1c
.RI "static int \fBrun_pa_loopback\fP (unsigned int sample_rate, unsigned int frames_per_buffer, const char *in_file, const char *out_file)"
.br
.ti -1c
.RI "static void \fBrun_loopback_null\fP (unsigned long count, unsigned int frames_per_buffer)"
.br
.ti -1c
.RI "static int \fBinit_pa\fP (\fBpa_user_data\fP *pa_data, unsigned int samp_rate, unsigned int frames_per_buffer)"
.br
.ti -1c
.RI "static int \fBclose_pa\fP ()"
.br
.ti -1c
.RI "static int \fBrun_pa_key\fP (\fBosp_user_data\fP *osp_data, unsigned int samp_rate, unsigned int frames_per_buffer, float attenuation_factor)"
.br
.ti -1c
.RI "static int \fBrun_pa_tcp\fP (\fBosp_user_data\fP *osp_data, unsigned int samp_rate, unsigned int frames_per_buffer, float attenuation_factor)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static \fBResample\fP \fBresampleL\fP"
.br
.RI "Resample structure for left channel\&. "
.ti -1c
.RI "static \fBResample\fP \fBresampleR\fP"
.br
.RI "Resample structure for right channel\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARRAY_SIZE(x)   (sizeof((x)) / sizeof((x)[0]))"

.SS "#define D_ATTENUATION_FACTOR   (0\&.025)"

.SS "#define FRAMES_PER_BUFFER   96"

.SS "#define OPT_STRING   'Enter \\'a\\' to enable hearing aid algorithm, \\'d\\' to disable \\'q\\' to quit\\n'"

.SS "#define SAMPLE_RATE   96000"

.SS "#define UI_PORT   8001"

.SH "Function Documentation"
.PP 
.SS "static void* announce_presence (void * tid)\fC [static]\fP"

.SS "static int close_pa ()\fC [static]\fP"

.SS "static int file_context_write (\fBfile_loopback_context\fP * file_ctx)\fC [static]\fP"

.SS "static void file_loopback_close (\fBfile_loopback_context\fP * ctx)\fC [static]\fP"

.SS "static int file_loopback_init (\fBfile_loopback_context\fP * ctx, const char * in_file, const char * out_file)\fC [static]\fP"

.SS "static int file_loopback_run (const char * in_file, const char * out_file, unsigned int frames_per_buffer)\fC [static]\fP"

.SS "static int init_pa (\fBpa_user_data\fP * pa_data, unsigned int samp_rate, unsigned int frames_per_buffer)\fC [static]\fP"

.SS "static float log2lin (float db)\fC [inline]\fP, \fC [static]\fP"

.SS "int main (int argc, char ** argv)"

.SS "static void run_loopback (\fBosp_user_data\fP * osp_data, float * inL, float * inR, float * outL, float * outR, size_t len)\fC [static]\fP"

.SS "static void run_loopback_null (unsigned long count, unsigned int frames_per_buffer)\fC [static]\fP"

.SS "static int run_pa_key (\fBosp_user_data\fP * osp_data, unsigned int samp_rate, unsigned int frames_per_buffer, float attenuation_factor)\fC [static]\fP"

.SS "static int run_pa_loopback (unsigned int sample_rate, unsigned int frames_per_buffer, const char * in_file, const char * out_file)\fC [static]\fP"

.SS "static int run_pa_tcp (\fBosp_user_data\fP * osp_data, unsigned int samp_rate, unsigned int frames_per_buffer, float attenuation_factor)\fC [static]\fP"

.SS "static void usage (const char * s)\fC [inline]\fP, \fC [static]\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBResample\fP resampleL\fC [static]\fP"

.PP
Resample structure for left channel\&. 
.SS "\fBResample\fP resampleR\fC [static]\fP"

.PP
Resample structure for right channel\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
