.TH "libosp/wdrc/mpo.c" 3 "Wed Jun 13 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp/wdrc/mpo.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mpo\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmpo\fP (float *input, float *pdB, float *wdrcdB, float mpo_limit, size_t len, float *out)"
.br
.RI "Function to apply dynamic-range compression to a single sub-band of the output of the analysis filter bank\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void mpo (float * input, float * pdB, float * wdrcdB, float mpo_limit, size_t len, float * out)"

.PP
Function to apply dynamic-range compression to a single sub-band of the output of the analysis filter bank\&. The peak detector output in dB SPL is needed as one of the inputs\&. The gain at 50 and 80 dB SPL is specified for the frequency sub-band, along with the lower and upper kneepoints in dB SPL\&. The compressor is linear below the lower kneepoint and applies compression limiting above the upper kneepoint
.PP
\fBParameters:\fP
.RS 4
\fIinput\fP Pointer to the signal array at the frequency sub-band (output from sub-band filtering) 
.br
\fIpdB\fP Pointer to the peak detector output array of the sub-band in dB SPL (output from peak_to_spl) 
.br
\fIwdrcdB\fP Gain in dB at the sub-band frequency for an input at 50 dB SPL 
.br
\fImpo_limit\fP Upper kneepoint in dB SPL for the sub-band 
.br
\fIlen\fP Length of the input array 
.br
\fIout\fP Pointer to an array where the compressed output of the sub-band will be written\&. i\&.e\&. the output of MPO limiter 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
