.TH "osp_tcp_t" 3 "Thu Jun 14 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
osp_tcp_t \- Data structure containing OSP TCP layer internal variables\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBconn_fd\fP"
.br
.RI "The socket file descriptor\&. "
.ti -1c
.RI "int \fBsock\fP"
.br
.RI "The socket in to establish a connection\&. "
.ti -1c
.RI "int \fBport\fP"
.br
.RI "The port to listen on for a connection\&. "
.in -1c
.SH "Detailed Description"
.PP 
Data structure containing OSP TCP layer internal variables\&. 
.SH "Field Documentation"
.PP 
.SS "int osp_tcp_t::conn_fd"

.PP
The socket file descriptor\&. 
.SS "int osp_tcp_t::port"

.PP
The port to listen on for a connection\&. 
.SS "int osp_tcp_t::sock"

.PP
The socket in to establish a connection\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
