.TH "pa_aux_data_t" 3 "Wed Jun 13 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pa_aux_data_t \- Struct that contains misc data passed to PortAudio\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <constants\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBunderruns\fP"
.br
.RI "Number of underruns detected by PortAudio\&. "
.ti -1c
.RI "float \fBattenuation_factor\fP"
.br
.ti -1c
.RI "float \fBgain_factor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct that contains misc data passed to PortAudio\&. 
.SH "Field Documentation"
.PP 
.SS "float pa_aux_data_t::attenuation_factor"

.SS "float pa_aux_data_t::gain_factor"

.SS "int pa_aux_data_t::underruns"

.PP
Number of underruns detected by PortAudio\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
