.TH "pa_loopback_data_t" 3 "Wed Jun 13 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pa_loopback_data_t \- Wraps around the osp_data, but also contains a file loopback context struct Have to wrap the two structs in one data structure so that we can pass it to the Port Audio callback\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <port_wrapper\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfile_loopback_context\fP * \fBfile_ctx\fP"
.br
.ti -1c
.RI "\fBosp_user_data\fP * \fBosp_data\fP"
.br
.ti -1c
.RI "unsigned char \fBdone\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wraps around the osp_data, but also contains a file loopback context struct Have to wrap the two structs in one data structure so that we can pass it to the Port Audio callback\&. 


.PP
\fBSee also:\fP
.RS 4
\fBfile_loopback_context\fP 
.PP
\fBosp_user_data\fP 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "unsigned char pa_loopback_data_t::done"

.SS "\fBfile_loopback_context\fP* pa_loopback_data_t::file_ctx"

.SS "\fBosp_user_data\fP* pa_loopback_data_t::osp_data"


.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
