.TH "pa_user_data_t" 3 "Thu Jun 14 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pa_user_data_t \- The data structure passed to PortAudio\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <constants\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBosp_user_data\fP * \fBuser_data\fP"
.br
.RI "Osp user data struct\&. "
.ti -1c
.RI "\fBpa_aux_data\fP \fBaux_data\fP"
.br
.RI "Auxiliary struct for misc data\&. "
.in -1c
.SH "Detailed Description"
.PP 
The data structure passed to PortAudio\&. 
.SH "Field Documentation"
.PP 
.SS "\fBpa_aux_data\fP pa_user_data_t::aux_data"

.PP
Auxiliary struct for misc data\&. 
.SS "\fBosp_user_data\fP* pa_user_data_t::user_data"

.PP
Osp user data struct\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
