.TH "peak_detect_t" 3 "Fri Feb 23 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peak_detect_t \- Peak Detect data structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBfsamp\fP"
.br
.RI "Sampling rate in Hz\&. "
.ti -1c
.RI "float * \fBprev_peak\fP"
.br
.RI "Pointer to the array of peak values of the last sample in previous frame for each band\&. "
.ti -1c
.RI "unsigned int \fBnum_bands\fP"
.br
.RI "Number of sub-bands\&. "
.in -1c
.SH "Detailed Description"
.PP 
Peak Detect data structure\&. 
.SH "Field Documentation"
.PP 
.SS "float peak_detect_t::fsamp"

.PP
Sampling rate in Hz\&. 
.SS "unsigned int peak_detect_t::num_bands"

.PP
Number of sub-bands\&. 
.SS "float* peak_detect_t::prev_peak"

.PP
Pointer to the array of peak values of the last sample in previous frame for each band\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
