.TH "osp/port_wrapper.c" 3 "Wed Jun 13 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
osp/port_wrapper.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'port_wrapper\&.h'\fP
.br
\fC#include 'resample\&.h'\fP
.br
\fC#include 'coeffs\&.h'\fP
.br
\fC#include 'beam_forming\&.h'\fP
.br
\fC#include 'utilities\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUM_INPUT_CHANNELS\fP   (2)"
.br
.ti -1c
.RI "#define \fBNUM_OUTPUT_CHANNELS\fP   (2)"
.br
.ti -1c
.RI "#define \fBPA_SAMPLE_TYPE\fP   (paFloat32|paNonInterleaved)"
.br
.ti -1c
.RI "#define \fBDESIRED_LATENCY\fP   (0\&.001)"
.br
.ti -1c
.RI "#define \fBDEVICE_USE\fP   (0)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static int \fB_internal_pa_init\fP (PaStreamParameters *inputParameters, PaStreamParameters *outputParameters, unsigned int sample_rate)"
.br
.ti -1c
.RI "static int \fBpa_main_callback\fP (const void *inputBuffer, void *outputBuffer, size_t frameCount, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)"
.br
.ti -1c
.RI "static int \fBpa_loopback_callback\fP (const void *inputBuffer, void *outputBuffer, unsigned long frameCount, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)"
.br
.ti -1c
.RI "int \fBpa_stop_stream\fP ()"
.br
.RI "Stops Port Audio stream\&. The audio callback will cease to be fired, stopping stream\&. "
.ti -1c
.RI "int \fBpa_loopback_run\fP (\fBpa_loopback_data\fP *loopback_data, unsigned int samp_rate, unsigned int frames_per_buffer)"
.br
.RI "Initialization for file loopback mode\&. Executes same functionality as pa_init\&. "
.ti -1c
.RI "int \fBpa_init\fP (\fBpa_user_data\fP *pa_data, unsigned int samp_rate, unsigned int frames_per_buffer)"
.br
.ti -1c
.RI "int \fBpa_start_stream\fP ()"
.br
.RI "Starts Port Audio stream\&. Until this is called, the audio callback will not be fired\&. "
.ti -1c
.RI "void \fBpa_close\fP ()"
.br
.RI "Closes Port Audio stream\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static PaStream * \fBstream\fP"
.br
.ti -1c
.RI "static PaError \fBerr_message\fP"
.br
.ti -1c
.RI "static \fBResample\fP \fBresampleL\fP"
.br
.ti -1c
.RI "static \fBResample\fP \fBresampleR\fP"
.br
.ti -1c
.RI "static \fBBeam_Form\fP \fBbeam_formL\fP"
.br
.ti -1c
.RI "static \fBBeam_Form\fP \fBbeam_formR\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DESIRED_LATENCY   (0\&.001)"

.SS "#define DEVICE_USE   (0)"

.SS "#define NUM_INPUT_CHANNELS   (2)"

.SS "#define NUM_OUTPUT_CHANNELS   (2)"

.SS "#define PA_SAMPLE_TYPE   (paFloat32|paNonInterleaved)"

.SH "Function Documentation"
.PP 
.SS "static int _internal_pa_init (PaStreamParameters * inputParameters, PaStreamParameters * outputParameters, unsigned int sample_rate)\fC [static]\fP"

.SS "void pa_close ()"

.PP
Closes Port Audio stream\&. 
.SS "int pa_init (\fBpa_user_data\fP * pa_data, unsigned int samp_rate, unsigned int frames_per_buffer)"

.SS "static int pa_loopback_callback (const void * inputBuffer, void * outputBuffer, unsigned long frameCount, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData)\fC [static]\fP"

.SS "int pa_loopback_run (\fBpa_loopback_data\fP * loopback_data, unsigned int samp_rate, unsigned int frames_per_buffer)"

.PP
Initialization for file loopback mode\&. Executes same functionality as pa_init\&. 
.PP
\fBSee also:\fP
.RS 4
\fBpa_loopback_data\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fIloopback_data\fP Structure that contains details about files (input and output), and samples 
.br
\fIsamp_rate\fP The sample rate of incoming/outgoing audio 
.br
\fIframes_per_buffer\fP The number of samples per buffer returned by PA\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 0 on success, -1 otherwise 
.RE
.PP

.SS "static int pa_main_callback (const void * inputBuffer, void * outputBuffer, size_t frameCount, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData)\fC [static]\fP"

.SS "int pa_start_stream ()"

.PP
Starts Port Audio stream\&. Until this is called, the audio callback will not be fired\&. 
.PP
\fBReturns:\fP
.RS 4
Returns 0 on success, -1 on error 
.RE
.PP

.SS "int pa_stop_stream ()"

.PP
Stops Port Audio stream\&. The audio callback will cease to be fired, stopping stream\&. 
.PP
\fBReturns:\fP
.RS 4
Returns 0 on success, -1 on error 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "\fBBeam_Form\fP beam_formL\fC [static]\fP"

.SS "\fBBeam_Form\fP beam_formR\fC [static]\fP"

.SS "PaError err_message\fC [static]\fP"

.SS "\fBResample\fP resampleL\fC [static]\fP"

.SS "\fBResample\fP resampleR\fC [static]\fP"

.SS "PaStream* stream\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
