.TH "osp/port_wrapper.h" 3 "Thu Jun 14 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
osp/port_wrapper.h
.SH SYNOPSIS
.br
.PP
\fC#include <portaudio\&.h>\fP
.br
\fC#include 'osp_process\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBfile_loopback_context_t\fP"
.br
.RI "Struct containing details for file loopback mode\&. "
.ti -1c
.RI "struct \fBpa_loopback_data_t\fP"
.br
.RI "Wraps around the osp_data, but also contains a file loopback context struct Have to wrap the two structs in one data structure so that we can pass it to the Port Audio callback\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBfile_loopback_context_t\fP \fBfile_loopback_context\fP"
.br
.RI "Struct containing details for file loopback mode\&. "
.ti -1c
.RI "typedef struct \fBpa_loopback_data_t\fP \fBpa_loopback_data\fP"
.br
.RI "Wraps around the osp_data, but also contains a file loopback context struct Have to wrap the two structs in one data structure so that we can pass it to the Port Audio callback\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpa_init\fP (\fBpa_user_data\fP *pa_data, unsigned int samp_rate, unsigned int frames_per_buffer)"
.br
.ti -1c
.RI "int \fBpa_loopback_run\fP (\fBpa_loopback_data\fP *loopback_data, unsigned int samp_rate, unsigned int frames_per_buffer)"
.br
.RI "Initialization for file loopback mode\&. Executes same functionality as pa_init\&. "
.ti -1c
.RI "int \fBpa_start_stream\fP ()"
.br
.RI "Starts Port Audio stream\&. Until this is called, the audio callback will not be fired\&. "
.ti -1c
.RI "int \fBpa_stop_stream\fP ()"
.br
.RI "Stops Port Audio stream\&. The audio callback will cease to be fired, stopping stream\&. "
.ti -1c
.RI "void \fBpa_close\fP ()"
.br
.RI "Closes Port Audio stream\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBfile_loopback_context_t\fP  \fBfile_loopback_context\fP"

.PP
Struct containing details for file loopback mode\&. 
.SS "typedef struct \fBpa_loopback_data_t\fP  \fBpa_loopback_data\fP"

.PP
Wraps around the osp_data, but also contains a file loopback context struct Have to wrap the two structs in one data structure so that we can pass it to the Port Audio callback\&. 
.PP
\fBSee also:\fP
.RS 4
\fBfile_loopback_context\fP 
.PP
\fBosp_user_data\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void pa_close ()"

.PP
Closes Port Audio stream\&. 
.SS "int pa_init (\fBpa_user_data\fP * pa_data, unsigned int samp_rate, unsigned int frames_per_buffer)"

.SS "int pa_loopback_run (\fBpa_loopback_data\fP * loopback_data, unsigned int samp_rate, unsigned int frames_per_buffer)"

.PP
Initialization for file loopback mode\&. Executes same functionality as pa_init\&. 
.PP
\fBSee also:\fP
.RS 4
\fBpa_loopback_data\fP
.RE
.PP
\fBParameters:\fP
.RS 4
\fIloopback_data\fP Structure that contains details about files (input and output), and samples 
.br
\fIsamp_rate\fP The sample rate of incoming/outgoing audio 
.br
\fIframes_per_buffer\fP The number of samples per buffer returned by PA\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Returns 0 on success, -1 otherwise 
.RE
.PP

.SS "int pa_start_stream ()"

.PP
Starts Port Audio stream\&. Until this is called, the audio callback will not be fired\&. 
.PP
\fBReturns:\fP
.RS 4
Returns 0 on success, -1 on error 
.RE
.PP

.SS "int pa_stop_stream ()"

.PP
Stops Port Audio stream\&. The audio callback will cease to be fired, stopping stream\&. 
.PP
\fBReturns:\fP
.RS 4
Returns 0 on success, -1 on error 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
