.TH "osp/scripts/read_taps.c" 3 "Wed Jun 13 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
osp/scripts/read_taps.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
