.TH "resample_t" 3 "Fri Feb 23 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
resample_t \- Data struct containing variables for resampler\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBFilter\fP \fBupsample\fP"
.br
.RI "Upsample filter\&. "
.ti -1c
.RI "\fBFilter\fP \fBdownsample\fP"
.br
.RI "downsample filter "
.in -1c
.SH "Detailed Description"
.PP 
Data struct containing variables for resampler\&. 
.SH "Field Documentation"
.PP 
.SS "\fBFilter\fP resample_t::downsample"

.PP
downsample filter 
.SS "\fBFilter\fP resample_t::upsample"

.PP
Upsample filter\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
