.TH "libosp/speech_enhancement/speech_enhancement.h" 3 "Fri Feb 23 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp/speech_enhancement/speech_enhancement.h
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include 'array_utilities\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBspeech_enhancement\fP (float *input, int ntype, int stype, float sparam, size_t len, int fsamp, float *out)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void speech_enhancement (float * input, int ntype, int stype, float sparam, size_t len, int fsamp, float * out)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
