.TH "libosp/osp_tcp/tcplib.c" 3 "Thu Jun 14 2018" "Open Speech Platform" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libosp/osp_tcp/tcplib.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <netinet/tcp\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include 'tcplib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBstart_tcp_server\fP (int port)"
.br
.RI "Starts the server side socket connection based on INET Internet stream-oriented sockets\&. "
.ti -1c
.RI "int \fBget_tcp_server_connection\fP (int sock)"
.br
.RI "Gets TCP protocol server\&. "
.ti -1c
.RI "int \fBclose_tcp_server_connection\fP (int connFd)"
.br
.RI "Closes TCP protocol server\&. "
.ti -1c
.RI "void \fBstop_tcp_server\fP (int sock)"
.br
.RI "Stops the TCP protocol server\&. "
.ti -1c
.RI "ssize_t \fBread_tcp_server_stream\fP (int connFd, char *recv_data, int len)"
.br
.RI "Reads data on server side\&. "
.ti -1c
.RI "int \fBstart_tcp_client\fP (char *ip, int port)"
.br
.RI "Initiates TCP protocol client\&. "
.ti -1c
.RI "int \fBstop_tcp_client\fP (int sock)"
.br
.RI "Stops TCP protocol client\&. "
.ti -1c
.RI "ssize_t \fBsend_tcp_client_data\fP (int sock, char *send_data, int len)"
.br
.RI "Sends data on client side\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int close_tcp_server_connection (int connFd)"

.PP
Closes TCP protocol server\&. 
.SS "int get_tcp_server_connection (int sock)"

.PP
Gets TCP protocol server\&. 
.SS "ssize_t read_tcp_server_stream (int connFd, char * recv_data, int len)"

.PP
Reads data on server side\&. 
.SS "ssize_t send_tcp_client_data (int sock, char * send_data, int len)"

.PP
Sends data on client side\&. 
.SS "int start_tcp_client (char * ip, int port)"

.PP
Initiates TCP protocol client\&. Starts the client side socket connection based on INET Internet stream-oriented sockets\&. 
.SS "int start_tcp_server (int port)"

.PP
Starts the server side socket connection based on INET Internet stream-oriented sockets\&. Initiates TCP protocol server\&. 
.SS "int stop_tcp_client (int sock)"

.PP
Stops TCP protocol client\&. 
.SS "void stop_tcp_server (int sock)"

.PP
Stops the TCP protocol server\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Open Speech Platform from the source code\&.
