#!/bin/bash

echo
echo
echo "This script will use 'sudo' throughout at various times, invoke this"
echo "as a user with sudo priveleges and enter your user password when prompted"
echo
echo

OS=$(uname)
if [ $OS = "Darwin" ]; then
  which -s brew
  if [[ $? != 0 ]]; then
    echo Install brew
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    brew update
  fi
  
  echo Install pre-requisite packages
  brew install -y portaudio poco cereal cmake pkg-config composer php72
elif [ $OS = "Linux" ]; then
  echo Install pre-requisite packages
  sudo apt-get update
  for i in alsa-base alsa-utils libasound2-dev portaudio19-dev \
          libpoco-dev libcereal-dev cmake sqlite sqlite3 php php-mbstring php-xml composer \
          zip unzip php-sqlite3; do
    sudo apt-get install -y $i
  done

fi

echo Build and install libosp
pushd libosp
mkdir -p build
cd build
cmake ..
make && sudo make install
popd

echo Build and install osp process
pushd OSP
mkdir -p build
cd build
cmake ..
make && sudo make install
popd

echo Build and install EWS
sudo mkdir -p /opt
sudo cp -r EWS /opt
sudo chown -R $(whoami) /opt/EWS
sudo sh -c 'printf "#!/bin/sh\n\n/opt/EWS/artisan serve --host=0.0.0.0\n" > /usr/local/bin/ews'
sudo chmod +x /usr/local/bin/ews
pushd /opt/EWS
touch database/homestead.sqlite
composer update
composer install
cp .env.example .env
php artisan config:cache
php artisan key:generate
php artisan config:cache
php artisan migrate
sudo chmod -R 777 /opt/EWS

echo
echo
echo "To run open two terminal windows, then in firset one run 'osp' and in the"
echo "second run 'ews'. Now open a browser window and goto http://localhost:8000"
echo "or type '-h' in the terminal running 'osp'."
echo
echo
