trigger:
  branches: {include: ['*'] }
  paths:
    include: ['*']
    exclude: ['docs/*', '.github/**']

stages:
- stage: build
  jobs:
  - job: manylinux2010
    pool: { vmImage: 'ubuntu-latest' }
    container: quay.io/pypa/manylinux2010_x86_64:latest
    steps:
    - bash: CFLAGS="-flto -static-libstdc++ -std=c++14" ./standalone_compilation_linux.sh
    - bash: strip --strip-unneeded liblsl.so
    - publish: liblsl.so
      artifact: manylinux2010

