-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.8
--/usr/local/diamond/3.10_x64/ispfpga/bin/lin64/scuba -w -n fmexg_fifo_8k_2049 -lang vhdl -synth synplify -bus_exp 7 -bb -arch xo3c00f -type ebfifo -depth 8192 -width 12 -rwidth 12 -no_enable -pe 10 -pf 2049 

-- Thu May  9 17:13:50 2019

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO3L;
use MACHXO3L.components.all;
-- synopsys translate_on

entity fmexg_fifo_8k_2049 is
    port (
        Data: in  std_logic_vector(11 downto 0); 
        WrClock: in  std_logic; 
        RdClock: in  std_logic; 
        WrEn: in  std_logic; 
        RdEn: in  std_logic; 
        Reset: in  std_logic; 
        RPReset: in  std_logic; 
        Q: out  std_logic_vector(11 downto 0); 
        Empty: out  std_logic; 
        Full: out  std_logic; 
        AlmostEmpty: out  std_logic; 
        AlmostFull: out  std_logic);
end fmexg_fifo_8k_2049;

architecture Structure of fmexg_fifo_8k_2049 is

    -- internal signal declarations
    signal scuba_vhi: std_logic;
    signal Empty_int: std_logic;
    signal Full_int: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component FIFO8KB
        generic (FULLPOINTER1 : in String; FULLPOINTER : in String; 
                AFPOINTER1 : in String; AFPOINTER : in String; 
                AEPOINTER1 : in String; AEPOINTER : in String; 
                ASYNC_RESET_RELEASE : in String; RESETMODE : in String; 
                GSR : in String; CSDECODE_R : in String; 
                CSDECODE_W : in String; REGMODE : in String; 
                DATA_WIDTH_R : in Integer; DATA_WIDTH_W : in Integer);
        port (DI0: in  std_logic; DI1: in  std_logic; DI2: in  std_logic; 
            DI3: in  std_logic; DI4: in  std_logic; DI5: in  std_logic; 
            DI6: in  std_logic; DI7: in  std_logic; DI8: in  std_logic; 
            DI9: in  std_logic; DI10: in  std_logic; DI11: in  std_logic; 
            DI12: in  std_logic; DI13: in  std_logic; 
            DI14: in  std_logic; DI15: in  std_logic; 
            DI16: in  std_logic; DI17: in  std_logic; 
            CSW0: in  std_logic; CSW1: in  std_logic; 
            CSR0: in  std_logic; CSR1: in  std_logic; 
            FULLI: in  std_logic; EMPTYI: in  std_logic; 
            WE: in  std_logic; RE: in  std_logic; ORE: in  std_logic; 
            CLKW: in  std_logic; CLKR: in  std_logic; RST: in  std_logic; 
            RPRST: in  std_logic; DO0: out  std_logic; 
            DO1: out  std_logic; DO2: out  std_logic; 
            DO3: out  std_logic; DO4: out  std_logic; 
            DO5: out  std_logic; DO6: out  std_logic; 
            DO7: out  std_logic; DO8: out  std_logic; 
            DO9: out  std_logic; DO10: out  std_logic; 
            DO11: out  std_logic; DO12: out  std_logic; 
            DO13: out  std_logic; DO14: out  std_logic; 
            DO15: out  std_logic; DO16: out  std_logic; 
            DO17: out  std_logic; EF: out  std_logic; 
            AEF: out  std_logic; AFF: out  std_logic; FF: out  std_logic);
    end component;
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    fmexg_fifo_8k_2049_0_11: FIFO8KB
        generic map (FULLPOINTER1=> "0b01111111111111", FULLPOINTER=> "0b10000000000000", 
        AFPOINTER1=> "0b00100000000000", AFPOINTER=> "0b00100000000001", 
        AEPOINTER1=> "0b00000000001011", AEPOINTER=> "0b00000000001010", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(0), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(0), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(0), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>Empty_int, AEF=>AlmostEmpty, AFF=>AlmostFull, 
            FF=>Full_int);

    fmexg_fifo_8k_2049_1_10: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111111", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111111", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111111", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(1), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(1), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(1), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    fmexg_fifo_8k_2049_2_9: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111111", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111111", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111111", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(2), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(2), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(2), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    fmexg_fifo_8k_2049_3_8: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111111", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111111", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111111", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(3), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(3), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(3), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    fmexg_fifo_8k_2049_4_7: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111111", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111111", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111111", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(4), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(4), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(4), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    fmexg_fifo_8k_2049_5_6: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111111", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111111", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111111", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(5), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(5), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(5), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    fmexg_fifo_8k_2049_6_5: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111111", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111111", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111111", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(6), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(6), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(6), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    fmexg_fifo_8k_2049_7_4: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111111", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111111", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111111", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(7), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(7), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(7), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    fmexg_fifo_8k_2049_8_3: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111111", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111111", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111111", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(8), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(8), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(8), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    fmexg_fifo_8k_2049_9_2: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111111", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111111", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111111", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(9), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(9), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(9), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    fmexg_fifo_8k_2049_10_1: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111111", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111111", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111111", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(10), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(10), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(10), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    fmexg_fifo_8k_2049_11_0: FIFO8KB
        generic map (FULLPOINTER1=> "0b00000000000000", FULLPOINTER=> "0b11111111111111", 
        AFPOINTER1=> "0b00000000000000", AFPOINTER=> "0b11111111111111", 
        AEPOINTER1=> "0b00000000000000", AEPOINTER=> "0b11111111111111", 
        ASYNC_RESET_RELEASE=> "SYNC", GSR=> "DISABLED", RESETMODE=> "ASYNC", 
        REGMODE=> "NOREG", CSDECODE_R=> "0b11", CSDECODE_W=> "0b11", 
        DATA_WIDTH_R=>  1, DATA_WIDTH_W=>  1)
        port map (DI0=>scuba_vlo, DI1=>Data(11), DI2=>scuba_vlo, 
            DI3=>scuba_vlo, DI4=>scuba_vlo, DI5=>scuba_vlo, 
            DI6=>scuba_vlo, DI7=>scuba_vlo, DI8=>scuba_vlo, 
            DI9=>scuba_vlo, DI10=>scuba_vlo, DI11=>Data(11), 
            DI12=>scuba_vlo, DI13=>scuba_vlo, DI14=>scuba_vlo, 
            DI15=>scuba_vlo, DI16=>scuba_vlo, DI17=>scuba_vlo, 
            CSW0=>scuba_vhi, CSW1=>scuba_vhi, CSR0=>scuba_vhi, 
            CSR1=>scuba_vhi, FULLI=>Full_int, EMPTYI=>Empty_int, 
            WE=>WrEn, RE=>RdEn, ORE=>RdEn, CLKW=>WrClock, CLKR=>RdClock, 
            RST=>Reset, RPRST=>RPReset, DO0=>Q(11), DO1=>open, DO2=>open, 
            DO3=>open, DO4=>open, DO5=>open, DO6=>open, DO7=>open, 
            DO8=>open, DO9=>open, DO10=>open, DO11=>open, DO12=>open, 
            DO13=>open, DO14=>open, DO15=>open, DO16=>open, DO17=>open, 
            EF=>open, AEF=>open, AFF=>open, FF=>open);

    Empty <= Empty_int;
    Full <= Full_int;
end Structure;

-- synopsys translate_off
library MACHXO3L;
configuration Structure_CON of fmexg_fifo_8k_2049 is
    for Structure
        for all:VHI use entity MACHXO3L.VHI(V); end for;
        for all:VLO use entity MACHXO3L.VLO(V); end for;
        for all:FIFO8KB use entity MACHXO3L.FIFO8KB(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
