#!/bin/bash

echo
echo
echo "This script will use 'sudo' throughout at various times, invoke this"
echo "as a user with sudo priveleges and enter your user password when prompted"
echo
echo

OS=$(uname)

echo Build, install and execute Nodejs-based EWS backend
sudo mkdir -p /opt
sudo cp -r ews-backend /opt
sudo chown -R $(whoami) /opt/ews-backend
sudo sh -c 'printf "#!/bin/sh\n\ncd /opt/ews-backend && npm run dev\n" > /usr/local/bin/ews-backend'
sudo chmod a+x /usr/local/bin/ews-backend
pushd /opt/ews-backend
sudo npm install
sudo npm update
sudo npm audit fix
sudo npm install -g sequelize-cli
#pushd $PWD/ews-backend 
sudo mkdir -p database
sudo sequelize db:migrate
popd
#popd



