#!/bin/bash

echo
echo
echo "This script will use 'sudo' throughout at various times, invoke this"
echo "as a user with sudo priveleges and enter your user password when prompted"
echo
echo

OS=$(uname)

echo Build and install librtmha
cd -
pushd librtmha
mkdir -p build
cd build
cmake ..
make && sudo make install
popd

echo Build and install osp process
pushd RTMHA
mkdir -p build
cd build
cmake ..
make && sudo make install
popd


